### ISSUE TITLE
"Physics camera count error. Please confirm whether all cameras are fastened"

### ISSUE THREAD

**Issue by Maleewich** [lllsondowlll/OP8_Camera#2]
I recently got this message after launching FactoryMode. Before that everything was fine.

Oneplus 8 pro
Oxygen OS 11.0.2.2.IN11BA
![Screenshot_20210112-172353](https://user-images.githubusercontent.com/29766781/104284999-ae710180-54fe-11eb-8f23-8768c8b96f42.png)

**Comment by lllsondowlll** [comment]
That doesn't appear to be a stock error, are you sure you haven't modified your phone software such as using a custom kernel or rom?

**Comment by lllsondowlll** [comment]
No response in over a month, closing
