### ISSUE TITLE
Emulator-5554 not found

### ISSUE THREAD

**Issue by Finnlife** [lllsondowlll/OP8_Camera#3]
There is an Error when I try to run the ./camera Script:

![image](https://user-images.githubusercontent.com/26007800/116795824-047eaa80-aad8-11eb-95ae-da1ec98582be.png)

**Comment by lllsondowlll** [comment]
Is ADB / Wifi ADB on?

**Comment by Finnlife** [comment]
Both enabled in the Developer-Settings

**Comment by lllsondowlll** [comment]
I'm seeing this issue now too. Seems the port for the ADB server has changed. Looking into it.

**Comment by quacksworth** [comment]
@lllsondowlll sorry to bug you, any fix yet?

**Comment by ghost** [comment]
Bump. Please fix this

**Comment by ricard0ff** [comment]
Bump, +1

**Comment by masllsam** [comment]
bump +1 year ;)

**Comment by lllsondowlll** [comment]
The dependencies were removed in OOS12 and I no longer own the phone, closing as repo is no longer maintained.
