### ISSUE TITLE
Wrong source.list URL?

### ISSUE THREAD

**Issue by Overter23** [lllsondowlll/OP8_Camera#4]
Have error on first step.

Skript:

![Screenshot_20210807-222819](https://user-images.githubusercontent.com/88592803/128608909-1f36a0d1-1ce1-45a5-ad30-1a37e7a0beb2.jpg)

**Comment by LeightonSolo** [comment]
Make sure you install termux from either the github or Fdroid. Otherwise the packages are outdated I think, I did the same thing
